import { put } from '@vercel/blob';
const MAX=40*1024*1024;
const validPackage=s=>/^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*)+$/.test(s)&&s.length<=180;
export const config={api:{bodyParser:false}};
async function parseMultipart(req){const chunks=[];for await(const c of req){chunks.push(c);if(Buffer.concat(chunks).length>MAX+1024*1024)throw new Error('Fichier trop volumineux (limite 40 Mo).');}const body=Buffer.concat(chunks);const ct=req.headers['content-type']||'';const boundary=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/)?.slice(1).find(Boolean);if(!boundary)throw new Error('Formulaire multipart invalide.');const raw=body.toString('latin1');const parts=raw.split('--'+boundary);const fields={};for(const p of parts){const i=p.indexOf('\r\n\r\n');if(i<0)continue;const head=p.slice(0,i),data=p.slice(i+4).replace(/\r\n$/,'').replace(/\r\n--$/,'');const nm=head.match(/name="([^"]+)"/)?.[1];if(!nm)continue;const fn=head.match(/filename="([^"]*)"/)?.[1];if(fn){const start=body.indexOf(Buffer.from('\r\n\r\n'),body.indexOf(Buffer.from('name="'+nm+'"')))+4;const end=body.indexOf(Buffer.from('\r\n--'+boundary),start);fields[nm]={filename:fn,buffer:body.subarray(start,end)};}else fields[nm]=data;}return fields;}
export default async function handler(req,res){if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Méthode non autorisée.'});}
try{const f=await parseMultipart(req);const appName=String(f.appName||'').trim(),packageId=String(f.packageId||''),version=String(f.version||''),type=String(f.sourceType||'');if(!appName||appName.length>40||!validPackage(packageId)||!/^\d+\.\d+\.\d+$/.test(version))return res.status(400).json({error:'Nom, package ou version invalide.'});if(!['link','html','zip'].includes(type))return res.status(400).json({error:'Type de source invalide.'});
let sourceUrl='';if(type==='link'){sourceUrl=String(f.url||'');let u;try{u=new URL(sourceUrl)}catch{}if(!u||!['http:','https:'].includes(u.protocol)||u.username||u.password)return res.status(400).json({error:'URL http(s) invalide.'});}
else{const file=f.file;if(!file?.buffer?.length)return res.status(400).json({error:'Fichier manquant.'});if(file.buffer.length>MAX)return res.status(413).json({error:'Fichier supérieur à 40 Mo.'});const isZip=type==='zip';if(isZip&&!file.buffer.subarray(0,4).equals(Buffer.from([0x50,0x4b,0x03,0x04])))return res.status(400).json({error:'Le fichier ne semble pas être un ZIP valide.'});if(!isZip&&!/\.html?$/i.test(file.filename))return res.status(400).json({error:'Le fichier doit être HTML.'});const blob=await put(`flowsx/${Date.now()}-${file.filename.replace(/[^a-zA-Z0-9._-]/g,'_')}`,file.buffer,{access:'public',addRandomSuffix:true,contentType:isZip?'application/zip':'text/html'});sourceUrl=blob.url;}
const owner=process.env.GITHUB_OWNER,repo=process.env.GITHUB_REPO,token=process.env.GITHUB_TOKEN;if(!owner||!repo||!token||!process.env.GITHUB_WORKFLOW)return res.status(500).json({error:'Configuration GitHub incomplète : ajoute GITHUB_OWNER, GITHUB_REPO, GITHUB_TOKEN et GITHUB_WORKFLOW dans Vercel.'});
const workflow=process.env.GITHUB_WORKFLOW,ref=process.env.GITHUB_REF||'main';const payload={ref,inputs:{app_name:appName,package_id:packageId,version,source_type:type,source_url:sourceUrl,internet:String(f.internet)==='true'?'true':'false'}};
const gh=await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/workflows/${encodeURIComponent(workflow)}/dispatches`,{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify(payload)});if(!gh.ok){const detail=await gh.text();return res.status(502).json({error:`GitHub a refusé le lancement (${gh.status}). Vérifie le token, les permissions Actions et le nom du workflow. ${detail.slice(0,180)}`});}
return res.status(200).json({ok:true,runUrl:`https://github.com/${owner}/${repo}/actions/workflows/${workflow}`,message:'Workflow dispatché.'});
}catch(e){return res.status(500).json({error:e.message||'Erreur serveur.'});}}
